### ISSUE TITLE
homepage/Onboarding page

### ISSUE THREAD

**Issue by PetraAG** [Mboalab/Mboacare_Main#1]
A user (both registered and unregistered should have the same homepage) with top navigation being the logo at the top left, and home, browse facility at the bottom, blog and profile. The homepage should be a scrollable page offering an overview of what the project is, the features and navigation. Some though not limited could be Want to register a medical facility (redirection), Want to browse through medical facilities (redirection), Read blogs (redirection), get to us,  and Follow us social media +++

**Comment by mercyjae** [comment]
I would like to work on this.
@PetraAG

**Comment by falyne** [comment]
Hello @PetraAG  I wish to work on this.

**Comment by PetraAG** [comment]
I can't find your task 2

**Comment by falyne** [comment]
> I can't find your task 2

I just made a PR this morning. It has not been merged

**Comment by PetraAG** [comment]
alright.. seen. Go ahead. The onboarding pages should be 3 to 5 sections max.

**Comment by falyne** [comment]
> alright.. seen. Go ahead. The onboarding pages should be 3 to 5 sections max.

Thanks
