### ISSUE TITLE
Settings/Profile page

### ISSUE THREAD

**Issue by PetraAG** [Mboalab/Mboacare_Main#6]
Such as name, username, password, image, medical facility management, change language etc.

**Comment by Kemyikpe** [comment]
please can this be assigned to me @PetraAG

**Comment by aprrrnl** [comment]
Since @Kemyikpe has went for 5, I can do this. @PetraAG

**Comment by bukky-eo** [comment]
I would like to work on this @PetraAG

**Comment by PetraAG** [comment]
@aprrrnl done

**Comment by PetraAG** [comment]
okay
