### ISSUE TITLE
Browse hospitals and blogs

### ISSUE THREAD

**Issue by PetraAG** [Mboalab/Mboacare_Main#7]
Map feature. Work with the person working on the form. or Work on the blogs page. Read or Submit blog. Blog title, author and read/ blog. Get intouch with the mentor for the form of submitting blog.

**Comment by larrytamnjong** [comment]
Hello @PetraAG  I will like to work on this issue..

**Comment by larrytamnjong** [comment]
@ngwa-harry I got this assigned this task but you can go ahead and work on it.

**Comment by ngwa-harry** [comment]
Since you've been assigned to it, just work on it. I haven't been assigned to it so I can't go ahead with it.
